export default {
  queryUserInfo: '/user',
  loginUser: 'POST /auth/login',
  logoutUser: '/auth/logout',

  queryEmailVerify: '/email/verify/:id/:hash',
  updateEmailResend: 'POST /email/resend',
  queryRouteList: '/routes',
  queryUser: '/users/:id',
  queryUserDetailsHeaderInfo: '/users/:id/headerInfo',
  queryUserPersonalInformation: '/users/:id/personalInfo',
  queryUserJobInformation: '/users/:id/jobInfo',
  queryUserRemuneration: '/users/:id/remuneration',
  queryUserContactInformation: '/users/:id/contactInfo',
  queryUserEducationInformation: '/users/:id/eduInfo',
  queryUserNotesInformation: 'POST /users/:id/notesInfo',
  queryUserFiles: '/users/:id/files',
  queryMoreInfo: '/users/:id/moreInfo',
  queryUserList: '/users/list',
  queryRoles: '/users/userRoles',
  queryTeamIds: '/users/teamIds',
  queryAllUsersList: '/users/export',
  queryUserSkills: '/users/userSkills',
  queryUserSoftSkills: '/users/userSoftSkills',
  queryUserPositions: '/users/userPositions',
  queryUserSalary: 'PUT /users/userSalary',
  querySelectedDayNote: '/users/:id/selectedDayNote',
  querySelectedMonthNotes: '/users/:id/selectedMonthNotes',
  updateUser: 'POST /users/update',
  updateUserDetails: 'POST /users/details',
  updateUserPersonalInformation: 'POST /users/personalInformation',
  updateJobInformation: 'POST /users/jobInformation',
  removeJobInformation: 'DELETE /users/removeJobInformation',
  createOrUpdateUniversityInformation: 'POST /users/universityInformation',
  createOrUpdateCollegeInformation: 'POST /users/collegeInformation',
  createOrUpdateSchoolInformation: 'POST /users/schoolInformation',
  updateLanguageInformation: 'POST /users/languageInformation',
  createOrUpdateMilitaryInformation: 'POST /users/militaryInformation',
  updateFiles: 'POST /users/files',
  removeEducation: 'DELETE /users/removeEducation',
  updateOrCreateNotesInformation: 'POST /users/userNotesInformation',
  queryForNoteActiveUsers: 'GET /users/queryForNoteActiveUsers',
  getCasualInformation: 'GET /users/getCasualInformation',
  createOrUpdateCasualInformation: 'POST /users/createOrUpdateCasualInformation',
  removeCasualInformation: 'DELETE /users/removeCasualInformation',
  removeNote: 'DELETE /users/removeNote',
  createUser: 'POST /users',
  createVacation: 'POST /users/vacation',
  updateVacation: 'POST /users/updateVacation',
  removeVacation: 'DELETE /users/removeVacation',
  createWorkHistory: 'POST /users/workHistory',
  removeUser: 'DELETE /users/:id',
  removeDocument: 'DELETE /users/removeDocument',
  removeUserList: 'POST /users/delete',
  updateUserEmail: 'PUT /users/updateUserEmail',
  queryPostList: '/posts',
  queryDashboard: '/dashboard',

  queryProject: '/projects/:id',
  queryProjectList: '/projects/list',
  queryProjectUsers: '/projects/users',
  queryProjectUserRoles: '/projects/userRoles',
  queryProjectTechnologies: '/projects/technologies',
  updateProjectMemberHistory: 'POST /projects/updateProjectMemberHistory',
  removeProjectMemberHistory: 'DELETE /projects/removeProjectMemberHistory',
  unassignedMemberFromProject: 'PUT /projects/unassignedMemberFromProject',
  queryProjectMemberHistory: '/projects/projectMemberHistory',
  queryProjectMembers: '/projects/projectMembers',
  updateProject: 'PUT /projects/:id',
  createProject: 'POST /projects',
  removeProject: 'DELETE /projects/:id',
  removeProjectList: 'POST /projects/delete',
  exportProjectsList: '/projects/export',

  queryTeamList: '/teams/list',
  queryTeamUsers: '/teams/users',
  queryProjects: '/teams/projects',
  queryTeams: '/teams/:id',
  teamsDetails: '/teams/teamsDetails/:id',
  updateTeam: 'Patch /teams/:id',
  createTeam: 'POST /teams',
  changeTeamStatus: 'POST /teams/changeTeamStatus',
  removeTeam: 'DELETE /teams/:id',
  removeTeamList: 'POST /teams/delete',
  queryMemberRoles:'GET /teams/memberRoles',
  exportTeamsList:'/teams/export',

  queryActiveProjectList: '/tasks/projectList',
  queryActiveTagsList: '/tasks/tagsList',
  queryWorkList: '/tasks/list',
  updateWork: 'PUT /tasks/:id',
  createWork: 'POST /tasks',
  start: 'POST /tasks/start',
  removeWork: 'DELETE /tasks/:id',
  removeWorkList: 'POST /tasks/delete',
  stopWork: 'POST /tasks/stop',
  startNewWork: 'POST /tasks/startNewWork',
  removeWorkTime: 'DELETE /tasks/removeWorkTime',
  submitOrResetDayReports: 'Patch /tasks/submitOrResetDayReports',
  getWorks: '/tasks/works',
  searchInWorks: '/tasks/search',
  getTags: '/tasks/getTags',
  createTag: 'POST /tasks/createTag',
  updateTag: 'Patch /tasks/tags/:id',
  deleteTag: 'DELETE /tasks/tags/:id',
  startWorkFromTodo: 'POST /tasks/startWorkFromTodo',
  startWorkFromFullCalendar: 'POST /tasks/startWorkFromFullCalendar',
  stopWorkFromFullCalendar: 'POST /tasks/stopWorkFromFullCalendar',
  addEventForFullCalendar: 'POST /tasks/addEventForFullCalendar',
  updateEventForFullCalendar: 'POST /tasks/updateEventForFullCalendar',

  queryReportList: '/reports/list',
  queryReportProjectsList: '/reports/projectsList',
  queryUserReportList: '/reports/userReport/list',
  queryReportProjectWorkList: '/reports/projectWorkList',
  queryReportProjectMemberList: '/reports/projectMemberList',
  queryReportDetailsList: '/reports/details/list',
  queryReportProjectList: '/reports/projects',
  queryReportFinancialList: '/reports/financial/list',
  queryReportTeamList: '/reports/teams',
  queryReportUserList: '/reports/users',
  queryReportProjectTimeList: '/reports/projectTimeList',
  queryReportProjectTimeExportData: '/reports/projectTimeExportData',
  exportFinancialReportList: '/reports/financial/export',
  exportSummaryReportList: '/reports/summary/export',
  exportDetailsReportList: '/reports/details/export',
  queryReportNowWorkingOnTasks: '/reports/nowWorkingOnTasks',
  queryReportEfforts: '/reports/efforts',

  queryDashboardReportList: '/dashboard/reportList',
  queryGetMostTracked: '/dashboard/mostTracked/:id',
  queryGetActivities: '/dashboard/activities',
  getWeeklyActivity: '/dashboard/weeklyActivity',
  getUserProjects: '/dashboard/getUserProjects',

  getComments: '/comments/getComments',
  storeComment: 'POST /comments/store',
  editComment: 'POST /comments/edit',
  deleteComment: 'DELETE /comments/delete',
  searchTask: 'POST /tasks/searchTask',

  updateActiveTask: 'POST /tasks/updateActiveTask',

  addSocialNetwork: 'POST /users/addSocialNetwork',
  addWebSite: 'POST /users/addWebSite',
  updateUserContactInformation: 'POST /users/updateUserContactInformation',
  deleteItemContactInfo: 'DELETE /users/deleteItemContactInfo',

  updateRemuneration: 'POST /users/updateRemuneration',
  remunerationUpdateJobType: 'POST /users/updateJobType',
  remunerationAddSalary: 'POST /users/addUserSalary',
  remunerationAddBonuses: 'POST /users/addUserBonus',
  remunerationUpdateBonus: 'POST /users/updateUserBonus',
  remunerationUpdateSalary: 'POST /users/updateUserSalary',
  deleteUserBonus: 'DELETE /user/deleteUserBonus',
  deleteUserSalary: 'DELETE /user/deleteUserSalary',

  uploadAvatar: 'POST /users/uploadAvatar',

  forgotPassword: 'POST /password/email',
  resetPassword: 'POST /password/reset',

  checkGoogleCalendarConnection: '/google/checkCalendarConnection/:id',
  addGoogleCalendarToken: 'POST /google/addCalendarToken/:id',
  removeGoogleCalendarToken: 'POST /google/removeCalendarToken/:id',
  queryGoogleAuthUrl: '/google/authUrl/:id',

  queryFullCalendar: '/users/fullCalendar',

  todosList: 'GET /todos/list',
  addTodo: 'POST /todos',
  showTodo: 'GET /todos/:id',
  updateTodo: 'PUT /todos/:id',
  deleteTodo: 'DELETE /todos/:id',
  totalTodos: 'GET /todos/totalTodos',

  userRegistration: 'POST /auth/registration',

  // now only administrator can do this
  queryUserRoles: 'GET /userRoles/roles',
  queryShowUserRole: 'GET /userRoles/show',
  createUserRole: 'POST /userRoles/roles',
  updateUserRole: 'PUT /userRoles/roles/:id',
  deleteUserRole: 'DELETE /userRoles/roles/:id',
  addPermissionToRole: 'POST /userRoles/addPermissionToRole',
  removePermissionFromRole: 'POST /userRoles/removePermissionFromRole',
  addDefaultPermissionsToRole: 'POST /userRoles/addDefaultPermissionsToRole',
  queryAllUserList: 'GET /userRoles/getAllUserList',
  assignUsersToRole: 'POST /userRoles/assignUsersToRole',
}
