import React from "react";
import PropTypes from 'prop-types';
import {
  Export,
  Plus,
  Calendar,
  Search,
  ArrowDown,
  ArrowUp,
  SortArrows,
  AntIcon,
  Dashboard,
  Works,
  Users,
  Projects,
  Teams,
  Reports,
  Bell,
  ArrowDown2,
  Pencil,
  Education,
  Military,
  Building,
  Job,
  File,
  Cart,
  Lock,
  Mail,
  MorePlus,
  Note,
  Person,
  Facebook,
  Instagram,
  Skype,
  Slack,
  Linkedin,
  Upload,
  DocumentDoc,
  DocumentPDF,
  DocumentPass,
  Close,
  Circle,
  PencilUnderLine,
  Trash,
  AsideToggle,
  LogOut,
  Settings,
  UserDashboard,
  Shared,
  Private,
  Edit,
  Delete,
  TwitterLogo,
  Tick,
  Info,
  Error,
  Success,
  MinusGradient,
  PlusGradient,
  SmallPencil,
  SmallDelete,
  Deactivate,
  TimerMode,
  ManualMode,
  Clock,
  List,
  Folders,
  Play,
  ManualEdit,
  Pause,
  Fb,
  In,
  Ln,
  Tw,
  ArrowLeft,
  Tag,
  Menu,
  CirclePicker,
  Dots,
  Camera,
  Phone,
  Paper,
  Web,
  LinkBroken,
  Link,
  FilterSliders,
} from './index';

const iconTypes = {
  export: Export,
  plus: Plus,
  calendar: Calendar,
  search: Search,
  arrowdown: ArrowDown,
  arrowUp: ArrowUp,
  arrowdown2: ArrowDown2,
  sortarrow: SortArrows,
  antIcon: AntIcon,
  dashboard: Dashboard,
  "clock-circle": Works,
  user: Users,
  project: Projects,
  team: Teams,
  "area-chart": Reports,
  "bar-chart": Dashboard,
  "pie-chart": Dashboard,
  message: Dashboard,
  bell: Bell,
  pencil: Pencil,
  education: Education,
  military: Military,
  building: Building,
  job: Job,
  file: File,
  cart: Cart,
  lock: Lock,
  mail: Mail,
  'more-plus': MorePlus,
  note: Note,
  person: Person,
  facebook: Facebook,
  instagram: Instagram,
  skype: Skype,
  slack: Slack,
  linkedin: Linkedin,
  upload: Upload,
  documentDoc: DocumentDoc,
  documentPDF: DocumentPDF,
  documentPass: DocumentPass,
  close: Close,
  circle: Circle,
  "pencil-underline": PencilUnderLine,
  trash: Trash,
  asideToggle: AsideToggle,
  logout: LogOut,
  settings: Settings,
  'user֊dashboard': UserDashboard,
  shared: Shared,
  private: Private,
  edit: Edit,
  delete: Delete,
  twitter: TwitterLogo,
  tick: Tick,
  info: Info,
  error: Error,
  success: Success,
  minusGradient: MinusGradient,
  plusGradient: PlusGradient,
  TimerMode: TimerMode,
  ManualMode: ManualMode,
  clock: Clock,
  list: List,
  'small-pencil': SmallPencil,
  'small-delete': SmallDelete,
  deactivate: Deactivate,
  folders: Folders,
  play: Play,
  manualEdit: ManualEdit,
  pause: Pause,
  fb:Fb,
  in: In,
  ln: Ln,
  tw: Tw,
  arrowLeft: ArrowLeft,
  tag: Tag,
  menu: Menu,
  circlePicker: CirclePicker,
  dots: Dots,
  camera: Camera,
  phone: Phone,
  paper: Paper,
  web: Web,
  linkBroken: LinkBroken,
  link: Link,
  filtersliders:FilterSliders,
};

const IconComponent = ({ name, ...props }) => {
  let Icon = iconTypes[name];
  return <Icon {...props} />;
};
IconComponent.propTypes = {
  name: PropTypes.string
};

export default IconComponent;
